name: 测试
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_on_ubuntu:
    name: 编译-ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

# 2.7.17 (x64)
# 3.5.9 (x64)
# 3.6.10 (x64)
# 3.7.6 (x64)
# 3.8.2 (x64)

    - name: 1. 安装Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: 2. pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt
        pip install -r requirements.txt

    - name: 3. check env
      run: |
        pwd || true
        which python3 || true && python3 --version || true
        pipdeptree || true

    - name: 4. run test
      run:
        env PYTHONPATH=$(pwd) python3 -m notify.wechat_qy


  #build_on_mac:
  #  name: 编译-on-mac
  #  runs-on: macOS-latest
  #  # 或macOS-10.14
  #
  #  steps:
  #  - name: 当前系统
  #    run: python --version